### ISSUE TITLE
Update links for Katharina and Matthias

### ISSUE THREAD

**Issue by KEggensperger** [automl-conf/automl-conf.github.io#107]
Hi, I just realized the [links](https://2023.automl.cc/organizers/) from the organizer info still point to Uni Freiburg for Matthias and me. Could you please update this to

Matthias Feurer --> https://www.slds.stat.uni-muenchen.de/people/feurer/
Katharina Eggensperger --> https://uni-tuebingen.de/en/research/core-research/cluster-of-excellence-machine-learning/research/research/cluster-research-groups/research-groups/automl-for-science/

Thank you!

**Comment by kozaka93** [comment]
Fixed, in the next update of the site will be visible :)
