### ISSUE TITLE
Early Bird registration Deadline

### ISSUE THREAD

**Issue by mlindauer** [automl-conf/automl-conf.github.io#110]
Hi,

Please add the early registration deadline to the website: July 13th
Both under "Dates" and on the front page.

Thanks,
Marius

**Comment by kozaka93** [comment]
Hi, 

In the date tab, should I write a sentence at the beginning of the page, create a new table with registration dates or add date to the Submission Timeline for Call for Papers?

Anna

**Comment by mlindauer** [comment]
A new table would be best. Thanks.
