### ISSUE TITLE
Highlighting reasons for attending the conference

### ISSUE THREAD

**Issue by mlindauer** [automl-conf/automl-conf.github.io#117]
Hi,

Frank and I believe that it would be best if the front page could also highlight some reasons for attending the conference. For example, on the AutoML fall school website https://sites.google.com/view/automl-fall-school-2022 (which you know of course), we had these "key features". Could you please make a proposal for adding something similar to the AUTOML conf front page.

Best,
Marius

**Comment by mlindauer** [comment]
Hi,

Any update on this? We would like to advertise the conference more this week and of course, it would tremendously help if interested attendees or sponsors would see the main points right away.
This could include:
* keynotes
* Tutorials
* Competitions
* Proceedings with accepted papers
* Sponsorships options 
* ...

Best,
Marius

**Comment by kozaka93** [comment]
Hi,

We were out of the office, but today evening we add this content to the website.

**Comment by woznicak** [comment]
Hi,

This is our proposition. We will work on a graphic illustration if something like this is appropriate.
- Insightful keynote presentations delivered by renowned experts in the field.
    
    *The keynotes provide valuable insights into the latest trends, challenges, and advancements in automated machine learning, making it a worthwhile experience for attendees.*
    
- Practical tutorials conducted by industry-leading professionals, providing attendees with hands-on learning opportunities.
    
    *These tutorials cover various AutoML techniques, tools, and best practices, equipping attendees with practical knowledge that they can apply in their own projects.*
    
- Cutting-edge competitions where participants showcase their novel AutoML models and algorithms.
    
    *Attending the conference allows you to witness these competitions firsthand, gaining exposure to cutting-edge solutions and innovative approaches developed by researchers and practitioners.*
    
- Opportunity to publication of accepted papers  in recognized journals as part of the conference proceedings
    
    *By submitting your work to the conference, you can share your latest research with the worldwide AutoML community, contributing to the collective knowledge and advancement of the field.* 
    
    *By attending the conference, you gain access to these papers, which offer in-depth knowledge and insights into the latest research findings, methodologies, and advancements in the AutoML domain.*
    
- An unique networking platform  to connect with like-minded individuals, share experiences, exchange ideas, and foster collaborations.
    
    *Conference attracts professionals, researchers, and enthusiasts from various domains and industries. These connections can lead to future collaborations, research partnerships, and career opportunities.*
    
- Exceptional opportunity for career growth in the fast-growing topic of AutoML.
    
    *By attending* workshops, and tutorials  *you can enhance your professional development, explore job opportunities, and stay ahead in the rapidly evolving field of automated machine learning.*
    
- A hub for the latest advancements in the field.
    
    *By attending the conference, you can stay updated on emerging AutoML techniques, algorithms, tools, and frameworks. This knowledge helps you remain at the forefront of the field, ensuring that you can leverage the latest developments in your own projects and research.*
