### ISSUE TITLE
Post pricing on the website

### ISSUE THREAD

**Issue by mfeurer** [automl-conf/automl-conf.github.io#118]
Currently, the website does not contain pricing information. It would be great if that could be listed on the website so that one knows the pricing prior to going through the registration system.

**Comment by kozaka93** [comment]
@mlindauer  what do you think about this? Add it to the Attend tab?

**Comment by mlindauer** [comment]
Yes, that's a good idea. It would be even better if we could also add the fees after the early registration deadline. @mfeurer do you know these?

**Comment by mfeurer** [comment]
No, sorry, I don't know these.

**Comment by mlindauer** [comment]
Here are all the fees:

EARLY BIRD (until July 13):
Non-student: 400
Student: 200
Virtual-only non-student: 50
Virtual-only student: 20 -> 0 (first 100)

AFTER EARLY BIRD:
Non-student: 500
Student: 300
Virtual-only non-student: 100
Virtual-only student: 50 -> 0 (first 100)

**Comment by woznicak** [comment]
@ma
