### ISSUE TITLE
Link to OR in Workshop CfP

### ISSUE THREAD

**Issue by mlindauer** [automl-conf/automl-conf.github.io#119]
Hi,

Could you please include the link to the workshop Openreview instance on the website, in the CfP for workshops https://openreview.net/group?id=automl.cc/AutoML/2023/Workshop_Track

Best,
Marius

**Comment by kozaka93** [comment]
Hi, 

We already have a link to OpenReview on the website, in the CfP for workshops.

Best, 
Anna

**Comment by mlindauer** [comment]
Sorry, never mind.
