### ISSUE TITLE
AutoML Cup phases 1 and 2 dates

### ISSUE THREAD

**Issue by nick11roberts** [automl-conf/automl-conf.github.io#129]
Hi there! We'd like to change the AutoML Cup phase 1 and 2 dates to the following. Thanks! 

**Phase 1:** June 6th - August 10th, 2023

**Phase 2:** July 15th — August 10th, 2023

**Comment by nick11roberts** [comment]
Hello! I noticed that on the website the phase 2 start date is still July 1, but we wanted to change it to July 15. We would like it to be:

**Phase 2:** July 15th — August 10th, 2023

**Comment by woznicak** [comment]
Great sorry, I missed that.
