### ISSUE TITLE
AutoML Cup update and phase 3

### ISSUE THREAD

**Issue by nick11roberts** [automl-conf/automl-conf.github.io#170]
Hello! 

We'd like to make the following changes to the AutoML Cup page:

1. We would like to change the start date of Phase 3 to be August 5. So it should now be:
**Phase 3:** August 5th — September 5th, 2023
2. We would like to remove the "FAQ" section. 
3. For the "Sponsors" section, we would like to add a line that says 
[American Family Insurance Data Science Institute](https://datascience.wisc.edu/institute/) at the University of Wisconsin-Madison
4. Under "Organizers," we would like to add a few people:
- Dyah Adila - University of Wisconsin-Madison
- Tzu-Heng Huang - University of Wisconsin-Madison
- Changho Shin - University of Wisconsin-Madison

Thank you!!!

**Comment by kozaka93** [comment]
Done :)
