### ISSUE TITLE
AutoML Cup phase 3 and phase 2 end date

### ISSUE THREAD

**Issue by nick11roberts** [automl-conf/automl-conf.github.io#182]
Hello! We would like to extend the end date of phase 2 and launch phase 3 of the AutoML Cup. 

For phase 2, we would like to update the end date to September 10th, 2023. 

We would also like to launch the AutoML Cup phase 3, along with new dates for this phase -- can we add the link to the competition on CodaBench onto the AutoML Cup page? I've included the text/link below for phase 3. Thank you!

Phase 3: August 10th — September 10th, 2023

The third and final phase will build on the first two phases but will additionally require handling situations in which access to labeled data is limited.
[Make your phase 3 submission here!](https://www.codabench.org/competitions/1232/)

**Comment by kozaka93** [comment]
Updated :)
