### ISSUE TITLE
Schedule does not sacle on mobile

### ISSUE THREAD

**Issue by alexandertornede** [automl-conf/automl-conf.github.io#210]
The schedule page does not scale well on mobile (https://2023.automl.cc/program/program/). This should really be fixed before the conference in order to make sure participants can properly have a look at the schedule on the phone during the conference.

**Comment by frank-hutter** [comment]
Could you please add times to the individual events in the schedule, to allow parsing the schedule on mobile?

And/or, as Roman proposed on Slack, break things out like

Tuesday
0900--1000: blah
1000--1200: blah blah
...
Wednesday
...
in addition
