### ISSUE TITLE
Typo in Title of "Oversampling to Repair Bias and Imbalance Simultaneously"

### ISSUE THREAD

**Issue by AndreBiedenkapp** [automl-conf/automl-conf.github.io#214]
The website falsely gives the title as
>Oversampling to Repair Bias and Imbalance **Together**

instead of 
>Oversampling to Repair Bias and Imbalance **Simultaneously**

**Comment by woznicak** [comment]
done in https://github.com/woznicak/automl_test_website/commit/38eacdc7dadf6ecc6e0c2dc41c5911c86929619
