### ISSUE TITLE
Add instructions on how to use Discord Search function

### ISSUE THREAD

**Issue by AndreBiedenkapp** [automl-conf/automl-conf.github.io#231]
I've added a simple explanation of how to use the Discord Search feature to find paper channels to https://ml.informatik.uni-freiburg.de/automl-conf-2023/
Can you please add the same instructions to "Poster Presentation Instructions"

**Comment by kozaka93** [comment]
The password that I have does not work :(

**Comment by AndreBiedenkapp** [comment]
I've sent you a DM in slack
