### ISSUE TITLE
Add links to individual paper channels on discord to the list of accepted papers

### ISSUE THREAD

**Issue by AndreBiedenkapp** [automl-conf/automl-conf.github.io#232]
I've made Anna Moderator on Discord. For every paper channel she should now be able to right-click on each channel, copy the link to that channel and add it to the list of accepted papers. That should make it easy to ask specific questions.

**Comment by kozaka93** [comment]
Do I understand correctly to add to the tab accepted papers add discord channel?

For example:
**Searching for Fairer Machine Learning Ensembles** - Michael Feffer, Martin Hirzel, Samuel C Hoffman, Kiran Kate, Parikshit Ram, Avraham Shinnar 
[OpenReview](https://openreview.net/forum?id=7Nbd1Ru1M_t) [PDF](https://openreview.net/pdf?id=7Nbd1Ru1M_t) [Video](https://www.youtube.com/watch?v=4tus7dtDpyY&list=PLp7L30nGpKM-6Y7LQdtb6TWX3o1d9BDSs&index=21&pp=iAQB) [Teaser](https://www.youtube.com/watch?v=_QvRrxOuGe8&list=PLp7L30nGpKM8_lzMdDbUnYXUlfBGH_EA2&index=19&pp=iAQB)  [Discord channel]() Room for poster presentation: D-Space

**Comment by AndreBiedenkapp** [comment]
Yes exactly :)
