### ISSUE TITLE
Quick update of text on schedule page

### ISSUE THREAD

**Issue by frank-hutter** [automl-conf/automl-conf.github.io#239]
On https://2023.automl.cc/program/program/
please update 

https://ml.informatik.uni-freiburg.de/automl-conf-2023/
The password will be sent to participants shortly before the conference.

This is a preliminary program. There may be minor updates to it in the coming weeks.
<actual schedule>

to 

Please click on each of the days for the daily program.

<actual schedule>

For online participation, you can find links to the sessions here: https://ml.informatik.uni-freiburg.de/automl-conf-2023/
The password for that page was emailed to registered participants on Friday, September 8.

**Comment by frank-hutter** [comment]
Sorry, what I wrote here didn't render well due to HTML :-(

I meant to put the second part of the text UNDERNEATH the schedule. Like this:


Please click on each of the days for the daily program.

ACTUAL SCHEDULE

For online participation, you can find links to the sessions here: https://ml.informatik.uni-freiburg.de/automl-conf-2023/
The password for that page was emailed to registered participants on Friday, September 8.

**Comment by kozaka93** [comment]
Ok, sorry for the misunderstanding. Now it should be fine.
