### ISSUE TITLE
Mihaela van der Schaar as Keynote Speaker

### ISSUE THREAD

**Issue by mlindauer** [automl-conf/automl-conf.github.io#25]
Hi,

The set of keynote speakers will be determined within the next weeks. I hope that we can announce one of them each week. The first one will be Mihaela van der Schaar. Can you please add here to the front page.

Best,
Marius

**Comment by kozaka93** [comment]
Hi, 

We have prepared a draft version for the Keynotes section, a preview is attached below. What do you think?

Best,
Anna

![obraz](https://user-images.githubusercontent.com/24189252/220200591-4a37c188-2ebc-4755-a3e7-5b26b5461529.png)

**Comment by mlindauer** [comment]
Hi,

Thanks. Looks nice! Are we able to add the talk titles later on?

Best,
Marius

**Comment by woznicak** [comment]
Yes, sure
