### ISSUE TITLE
[2022] Links to Papers: Late-Breaking Workshop

### ISSUE THREAD

**Issue by woznicak** [automl-conf/automl-conf.github.io#27]
The links to papers  Late-Breaking Workshop does not work https://2022.automl.cc/index.html%3Fp=615.html
Do we able to fix this?

**Comment by mlindauer** [comment]
Hi, for me the link is working.

**Comment by woznicak** [comment]
![image](https://user-images.githubusercontent.com/32644095/220885420-c6fb303b-48b1-4e8a-8b7f-addc035a882f.png)
@mlindauer I meant the links to the pdf version of paper (let's see at screen). These links redirect to the this year conference

**Comment by mlindauer** [comment]
Hi,

Thanks for noting.
I hope this is fixed now.

Best
Marius
