### ISSUE TITLE
Change Ethic Guidelines

### ISSUE THREAD

**Issue by mlindauer** [automl-conf/automl-conf.github.io#29]
Please change a sentence in the ethic guidelines

> "ICML has developed these guidelines in collaboration with the NAACL 2022 team, and the [NAACL 2022 blog post](https://2022.naacl.org/blog/publication-accessibility-quality-inclusivity/) contains additional details and resources."

should be 

>  "As mentioned above, for this part of the guidelines we follow ICML's process. ICML has [...]"

Thanks,
Marius

**Comment by kozaka93** [comment]
Fix #28
