### ISSUE TITLE
Keynote Speakers

### ISSUE THREAD

**Issue by mlindauer** [automl-conf/automl-conf.github.io#30]
Hi,

We have a (complete?) list of invited speakers now:

* ~~Eytan Bakshy~~
  * http://eytan.github.io/
  * affiliation: meta
  * Photo from his website
* ~~Hayeon Lee~~
  * https://hayeonlee.github.io/
  * affiliation: KAIST  
  * Photo from her website
* Esteban Real
  * https://sites.google.com/site/estebanalbertoreal/home
  * affiliation: google
  * photo: TBD
* Madeleine Udell  
  *  https://web.stanford.edu/~udell/
  * affiliation: Stanford University
  * photo:  https://web.stanford.edu/~udell/img/20160820_udell_crop.jpg

I would like to announce these over the next weeks -- in the order above. So, could you please prepare PRs for each of them.

~~Please also add the affiliation of Mihaela.~~

Best,
Marius

**Comment by mlindauer** [comment]
Hi,

I would love to do the next announcement tomorrow and then soonish the next one. Could you please prepare the PRs soon.

There will also be some more new stuff for the website soon -- important sprint before the submission deadline in a few weeks for all of us.

Best,
Marius

**Comment by woznicak** [comment]
Yes, I will prepare the first keynote today, it is almost ready. Before 8pm PR will be ready today

**Comment by mlindauer** [comment]
Great! Thank you!
Can we please continue with the Hayeon tomorrow

**Comment by woznicak** [comment]
@mlindauer, do you know which photo we can use for Esteban Real?

**Comment by mlindauer** [comment]
Unfortunately, no. He became farther last week and is super busy right now. He could only promise me details by Monday.

**Comment by mlindauer** [comment]
maybe let's continue with Madeleine first

**Comment by mlindauer** [comment]
Esteban Real

![esteban_real_profile_photo](https://user-images.githubusercontent.com/5947529/223162132-2f1c9c77-31d9-4176-8b27-2386090c9146.jpg)

Affiliation to show
Google Research

Link to include
[www.estebanreal.com](http://www.estebanreal.com/)

**Comment by woznicak** [comment]
we've added Madeleine Udell first #40

**Comment by woznicak** [comment]
we've added E.Real
