### ISSUE TITLE
Competition

### ISSUE THREAD

**Issue by mlindauer** [automl-conf/automl-conf.github.io#50]
Hi,

This is only a heads-up that there will be a competition call, too.
There is still no final go for it, but to keep track of it, let me mention it already

The website should be:
[2023.automl.cc/automl-cup](http://2023.automl.cc/automl-cup)

Content:
https://docs.google.com/document/d/1Z5ge6qbuorH5gEakr3f0rJxb4ZHQq5lwOMlxUrh2TKo/edit

Best,
Marius

**Comment by woznicak** [comment]
I've prepared the draft of the AutoML Cup tab and we have that on the test repo (which is private). Let me know when you plan to publish it and I'll add new branch

**Comment by nick11roberts** [comment]
Yep, we are ready to announce! Sounds good on our end.

**Comment by woznicak** [comment]
@nick11roberts , we've already added that to the website
