### ISSUE TITLE
Reviewer Registration

### ISSUE THREAD

**Issue by mlindauer** [automl-conf/automl-conf.github.io#57]
Hi,

Could you please rename the "Reviewer Form" button with "Reviewer Registration".
Furthermore, please still overlook it and write emails to Frank directly. Can we somehow add a banner or something similar "impossible to miss" to the website?

Best,
Marius

**Comment by kozaka93** [comment]
> Furthermore, please still overlook it and write emails to Frank directly. Can we somehow add a banner or something similar "impossible to miss" to the website?

This is unclear for me, could you please clarify it?
