### ISSUE TITLE
AutoML Cup updates

### ISSUE THREAD

**Issue by nick11roberts** [automl-conf/automl-conf.github.io#85]
Hello! I've added two PRs: #83 which pushes back the AutoML Cup timeline (new launch date is June 1), and #84 which adds prize information.

**Comment by kozaka93** [comment]
Hi,
Thank you for the update. I appreciate you changing the .html files; however, please provide the text you put in the .html. I need to update the developer version, which will automatically generate the .html files.

**Comment by nick11roberts** [comment]
Got it! Here's are the two sections. Thank you!!! 

**Prizes**
Winning teams will be awarded exciting hardware!!!

To be eligible for prizes, you must make a submission for each of the three competition phases and make your submission open source at the conclusion of each phase. After the competition, the top ranked teams will also be featured in a retrospective paper that dives into the results and key takeaways of the competition.

To avoid conflicts of interest, all competition organizers are ineligible for prizes.

**Important Dates**

The AutoML Cup will include three phases.

**Phase 1:** June 1st - July 5th, 2023

The first phase will emphasize diverse 1D tasks.

**Phase 2:** July 1st - August 5th, 2023

The second phase will expand beyond 1D tasks to include tasks with different input dimensionalities.

**Phase 3:** August 1st - September 5th, 2023

The third and final phase will build on the first two phases but will additionally require handling situations in which access to labeled data is limited.

**Comment by kozaka93** [comment]
Fix #83 #84
